apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 8080

