apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 8080
      protocol: TCP
      name: grpc

