apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: gcr.io/google-samples/microservices-demo/adservice:v0.8.0
        ports:
        - containerPort: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: demo
spec:
  selector:
    app: adservice
  ports:
  - port: 9555
    targetPort: 9555
