apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: demo
spec:
  selector:
    app: cart
  ports:
  - port: 7070
    targetPort: 7070
