apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.8.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: demo
spec:
  selector:
    app: emailservice
  ports:
  - port: 5000
    targetPort: 5000
