apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
      - name: productcatalog
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
        ports:
        - containerPort: 3550

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: demo
spec:
  selector:
    app: productcatalog
  ports:
  - port: 3550
    targetPort: 3550
