apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservice
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.8.0
        ports:
        - containerPort: 8080
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"

---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: demo
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
    targetPort: 8080
