apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.8.0
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: demo
spec:
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051
